#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <math.h>

#include <ucdr/microcdr.h>
#include "generated/MotorStatus.h"
#include "generated/Frame.h"

// Float comparison helper
static bool float_eq(float a, float b) {
    return fabsf(a - b) < 1e-5f;
}

static void test_motor_status_roundtrip(void) {
    printf("[TEST] Running test_motor_status_roundtrip...\n");

    // 1. Prepare original data
    robot_msgs_MotorStatus original = {
        .sequence = 123456,
        .velocity = 3.141592f,
        .current = -2.71828f,
        .position = {10.5f, -20.25f, 30.125f},
        .is_enabled = true
    };

    // 2. Serialize
    uint8_t buffer[256];
    memset(buffer, 0xFF, sizeof(buffer)); // Fill with sentinel
    ucdrBuffer writer;
    ucdr_init_buffer(&writer, buffer, sizeof(buffer));

    bool ser_ok = robot_msgs_MotorStatus_serialize(&writer, &original);
    assert(ser_ok == true);

    size_t serialized_len = ucdr_buffer_length(&writer);
    printf("       Serialized length: %zu bytes\n", serialized_len);

    // 3. Verify CDR Header manually
    // CDR Little Endian header: 0x00, 0x01, 0x00, 0x00
    assert(buffer[0] == 0x00);
    assert(buffer[1] == 0x01);
    assert(buffer[2] == 0x00);
    assert(buffer[3] == 0x00);

    // 4. Deserialize
    robot_msgs_MotorStatus restored;
    memset(&restored, 0, sizeof(restored));
    ucdrBuffer reader;
    ucdr_init_buffer(&reader, buffer, serialized_len);

    bool deser_ok = robot_msgs_MotorStatus_deserialize(&reader, &restored);
    assert(deser_ok == true);

    // 5. Assert equality
    assert(restored.sequence == original.sequence);
    assert(float_eq(restored.velocity, original.velocity));
    assert(float_eq(restored.current, original.current));
    assert(float_eq(restored.position[0], original.position[0]));
    assert(float_eq(restored.position[1], original.position[1]));
    assert(float_eq(restored.position[2], original.position[2]));
    assert(restored.is_enabled == original.is_enabled);

    printf("       test_motor_status_roundtrip: PASSED ✅\n");
}

static void test_can_msgs_frame_roundtrip(void) {
    printf("[TEST] Running test_can_msgs_frame_roundtrip...\n");

    can_msgs_Frame original = {
        .header = {
            .sec = 12345,
            .nanosec = 67890,
            .frame_id = "can_bus_0"
        },
        .id = 0x7E8,
        .is_rtr = false,
        .is_extended = false,
        .is_error = false,
        .dlc = 8,
        .data = {0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
    };

    uint8_t buffer[256];
    memset(buffer, 0, sizeof(buffer));
    ucdrBuffer writer;
    ucdr_init_buffer(&writer, buffer, sizeof(buffer));

    bool ser_ok = can_msgs_Frame_serialize(&writer, &original);
    assert(ser_ok == true);

    size_t serialized_len = ucdr_buffer_length(&writer);
    printf("       Serialized length: %zu bytes\n", serialized_len);

    // Verify CDR header
    assert(buffer[0] == 0x00);
    assert(buffer[1] == 0x01);
    assert(buffer[2] == 0x00);
    assert(buffer[3] == 0x00);

    can_msgs_Frame restored;
    memset(&restored, 0, sizeof(restored));
    ucdrBuffer reader;
    ucdr_init_buffer(&reader, buffer, serialized_len);

    bool deser_ok = can_msgs_Frame_deserialize(&reader, &restored);
    assert(deser_ok == true);

    assert(restored.header.sec == original.header.sec);
    assert(restored.header.nanosec == original.header.nanosec);
    assert(strcmp(restored.header.frame_id, original.header.frame_id) == 0);
    assert(restored.id == original.id);
    assert(restored.is_rtr == original.is_rtr);
    assert(restored.is_extended == original.is_extended);
    assert(restored.is_error == original.is_error);
    assert(restored.dlc == original.dlc);
    assert(memcmp(restored.data, original.data, 8) == 0);

    printf("       test_can_msgs_frame_roundtrip: PASSED ✅\n");
}

static void test_can_msgs_frame_from_external_bytes(void) {
    printf("[TEST] Running test_can_msgs_frame_from_external_bytes...\n");

    // Exact bytes generated by ROS 2 / Python simulation:
    // header: sec=123, nanosec=456, frame_id="can0"
    // id=0x123, is_rtr=0, is_extended=1, is_error=0, dlc=8, data=[1..8]
    static const uint8_t raw_cdr[] = {
        0x00, 0x01, 0x00, 0x00, 0x7b, 0x00, 0x00, 0x00,
        0xc8, 0x01, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00,
        0x63, 0x61, 0x6e, 0x30, 0x00, 0x00, 0x00, 0x00,
        0x23, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x08,
        0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08
    };

    can_msgs_Frame frame;
    memset(&frame, 0, sizeof(frame));
    ucdrBuffer reader;
    ucdr_init_buffer(&reader, (uint8_t *)raw_cdr, sizeof(raw_cdr));

    bool ok = can_msgs_Frame_deserialize(&reader, &frame);
    assert(ok == true);

    assert(frame.header.sec == 123);
    assert(frame.header.nanosec == 456);
    assert(strcmp(frame.header.frame_id, "can0") == 0);
    assert(frame.id == 0x123);
    assert(frame.is_rtr == false);
    assert(frame.is_extended == true);
    assert(frame.is_error == false);
    assert(frame.dlc == 8);
    for (int i = 0; i < 8; i++) {
        assert(frame.data[i] == (i + 1));
    }

    printf("       test_can_msgs_frame_from_external_bytes: PASSED ✅\n");
}

static void test_buffer_overflow_protection(void) {
    printf("[TEST] Running test_buffer_overflow_protection...\n");

    robot_msgs_MotorStatus data = {
        .sequence = 1,
        .velocity = 1.0f,
        .current = 1.0f,
        .position = {0.0f, 0.0f, 0.0f},
        .is_enabled = false
    };

    // Buffer too small (only 4 bytes, cannot even fit full CDR payload)
    uint8_t tiny_buffer[4];
    ucdrBuffer writer;
    ucdr_init_buffer(&writer, tiny_buffer, sizeof(tiny_buffer));

    bool ser_ok = robot_msgs_MotorStatus_serialize(&writer, &data);
    assert(ser_ok == false); // Must fail safely!

    printf("       test_buffer_overflow_protection: PASSED ✅\n");
}

static void test_keyexpr_macro(void) {
    printf("[TEST] Running test_keyexpr_macro...\n");

    const char *ke = robot_msgs_MotorStatus_KEYEXPR("0", "my_motor");
    assert(ke != NULL);
    assert(strstr(ke, "0/my_motor/") != NULL);
    assert(strstr(ke, "robot_msgs::msg::dds_::MotorStatus_") != NULL);
    assert(strstr(ke, "RIHS01_") != NULL);

    printf("       MotorStatus KeyExpr: %s\n", ke);

    const char *ke_can = can_msgs_Frame_KEYEXPR("0", "can_msgs/frame");
    assert(ke_can != NULL);
    assert(strstr(ke_can, "0/can_msgs/frame/") != NULL);
    assert(strstr(ke_can, "can_msgs::msg::dds_::Frame_") != NULL);
    assert(strstr(ke_can, "RIHS01_0cdc7d15657573ee6ff151e5cc1943888301e370d957e2c077a154f4755fd976") != NULL);

    printf("       Frame KeyExpr      : %s\n", ke_can);
    printf("       test_keyexpr_macro: PASSED ✅\n");
}

int main(void) {
    printf("========================================\n");
    printf("   Micro-CDR Serialization Unit Tests   \n");
    printf("========================================\n");

    test_motor_status_roundtrip();
    test_can_msgs_frame_roundtrip();
    test_can_msgs_frame_from_external_bytes();
    test_buffer_overflow_protection();
    test_keyexpr_macro();

    printf("========================================\n");
    printf("   ALL UNIT TESTS PASSED SUCCESSFULLY!  \n");
    printf("========================================\n");
    return 0;
}
